version: 40
jobs:
- name: Push to Github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/KimYoungNo/ttyd-service.git
    userName: KimYoungNo
    passwordSecret: access-token
    force: false
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
