version: 40
jobs:
- name: Push to Github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/KimYoungNo/ttyd-service.git
    userName: KimYoungNo
    passwordSecret: access-token
    force: false
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Pull from Github
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/KimYoungNo/ttyd-service.git
    userName: KimYoungNo
    passwordSecret: access-token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: SUCCESSFUL
    optional: false
  jobExecutor: shell
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
